spring:

  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${TICKETS_DB_URL}
    username: ${TICKETS_DB_USER}
    password: ${TICKETS_DB_PW}

  jpa:
    database: mysql
    show-sql: false
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: false
        show_sql: false
        globally_quoted_identifiers: false
    generate-ddl: true
    database-platform: org.hibernate.dialect.MySQL8Dialect

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

cloud:
  aws:
    s3:
      bucket: tickets2323
    credentials:
      access-key: ${TICKETS_S3_ACCESS}
      secret-key: ${TICKETS_S3_SECRET}
    region:
      static: ap-northeast-2
      auto: false
    stack:
      auto: false

logging:
  level:
    project.backend: debug

jwt:
  secret: ${TICKETS_SECRET}
  kakao:
    client_id: ${TICKETS_CLIENT}

server:
  port: 443
  error:
    include-exception: true     # 응답에 exception의 내용을 포함할지 여부
    path: '/error'               # 응답을 처리할 Handler의 경로
    whitelabel:
      enabled: true             # 서버 오류 발생시 브라우저에 보여줄 기본 페이지 생성 여부
  #    include-message: always
  ssl:
    key-store: classpath:keystore.p12
    key-store-type: PKCS12
    key-alias: ticats
    key-store-password: ${TICATS_SSL_PW}
    enabled: true